spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: game-stats
          uri: lb://game-stats
          predicates:
            - Path=/gamestats/**
#          filters:
#            - RewritePath=/gamestats/(?<path>.*), /$\{path}
#           #Method=GET
#            
        - id: single-game
          uri: lb://single-game # can also place direct uri (localhost:8201/)
          predicates:
            - Path=/game/**